In [33]:
import pandas as pd

In [34]:
#load the file 

disaster_data_to_load = "natural_disasters.csv"

disaster_df = pd.read_csv(disaster_data_to_load)
disaster_df.head()

,Declaration Number,Declaration Type,Declaration Date,State,County,Disaster Type,Disaster Title,Start Date,End Date,Individual Assistance Program,Individuals & Households Program,Public Assistance Program,Hazard Mitigation Program
0,DR-1992,Disaster,6/10/11,AK,Crooked Creek ANV/ANVSA,Flood,Ice Jam and Flooding,5/8/11,5/13/11,No,No,Yes,Yes
1,DR-1992,Disaster,6/10/11,AK,Kuspuk Regional Educational Attendance Area,Flood,Ice Jam and Flooding,5/8/11,5/13/11,No,No,Yes,Yes
2,DR-1992,Disaster,6/10/11,AK,Red Devil ANV/ANVSA,Flood,Ice Jam and Flooding,5/8/11,5/13/11,No,No,Yes,Yes
3,DR-4050,Disaster,12/22/11,AK,Bering Strait Regional Educational Attendance ...,Storm,Severe Winter Storms and Flooding,11/8/11,11/13/11,No,No,Yes,Yes
4,DR-4050,Disaster,12/22/11,AK,Lower Kuskokwim Regional Educational Attendanc...,Storm,Severe Winter Storms and Flooding,11/8/11,11/13/11,No,No,Yes,Yes

In [35]:
print (len(disaster_df))

6547

In [36]:
#how many disasters per year 

disaster_df['year start'] = pd.DatetimeIndex(disaster_df['Start Date']).year
disaster_df['year end'] = pd.DatetimeIndex(disaster_df['End Date']).year
disaster_df.dropna
disaster_df.tail()

,Declaration Number,Declaration Type,Declaration Date,State,County,Disaster Type,Disaster Title,Start Date,End Date,Individual Assistance Program,Individuals & Households Program,Public Assistance Program,Hazard Mitigation Program,year start,year end
6542,DR-4007,Disaster,7/22/11,WY,Weston County,Storm,"Severe Storms, Flooding, and Landslides",5/18/11,7/8/11,No,No,Yes,Yes,2011,2011
6543,DR-4227,Disaster,7/7/15,WY,Albany County,Flood,Severe Storms and Flooding,5/24/15,6/6/15,No,Yes,Yes,Yes,2015,2015
6544,DR-4227,Disaster,7/7/15,WY,Johnson County,Flood,Severe Storms and Flooding,5/24/15,6/6/15,No,Yes,Yes,Yes,2015,2015
6545,DR-4227,Disaster,7/7/15,WY,Niobrara County,Flood,Severe Storms and Flooding,5/24/15,6/6/15,No,Yes,Yes,Yes,2015,2015
6546,DR-4227,Disaster,7/7/15,WY,Platte County,Flood,Severe Storms and Flooding,5/24/15,6/6/15,No,Yes,Yes,Yes,2015,2015

In [37]:
print (len(disaster_df))

6547

In [38]:
disaster_clean_df = disaster_df[[ "State","Disaster Type" , "Disaster Title", "year start", "year end" ]]
disaster_clean_df.head()

  State Disaster Type                     Disaster Title  year start  year end
0    AK         Flood               Ice Jam and Flooding        2011      2011
1    AK         Flood               Ice Jam and Flooding        2011      2011
2    AK         Flood               Ice Jam and Flooding        2011      2011
3    AK         Storm  Severe Winter Storms and Flooding        2011      2011
4    AK         Storm  Severe Winter Storms and Flooding        2011      2011

In [55]:
disaster_clean_df.to_csv("disasters_clean.csv")